version: '3'

services:
  postfix:
    image: phplist/postfix
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    hostname: localhost  
    volumes:
      - ./postfix-main.cf:/etc/postfix/main.cf
    environment:
      MAIL_DOMAIN: localhost  
    network_mode: host

