version: '3'

services:
  postfix:
    build: .
    hostname: mail.example.com  
    volumes:
      - ./postfix-main.cf:/etc/postfix/main.cf
      - ./postfix-master.cf:/etc/postfix/master.cf
    environment:
      MAIL_DOMAIN: example.com  
    network_mode: host
    dns:
      - 100.64.85.13  

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
